services:
  portafolioDB:
    image: postgres:15.3
    container_name: portafolio-db # Cambiar el nombre del contenedor
    restart: always
    ports:
      - 5438:5432    # Escoger el puerto adecuado, por ejemplo de 5432:5432 a 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data